### ISSUE TITLE
执行 fis relese -p 后，产出的 pkg 文件夹中缺少合并后的 index.js 

### ISSUE THREAD

**Issue by BelinChung** [fex-team/fis-components-demo#1]
```
➜  ~  fis -v

  v1.9.11
➜  ~  npm -g list | grep depscombine
├── fis-packager-depscombine@0.0.8
```

**Comment by oxUnd** [comment]
配置怎么写的？

**Comment by BelinChung** [comment]
@xiangshouding 这个 demo 也能复现。

**Comment by 2betop** [comment]
没搞明白啊， index.js 在哪啊？

**Comment by BelinChung** [comment]
意思是打包之后之后没有合并的 index.js 吗？

![qq20150407-1 2x](https://cloud.githubusercontent.com/assets/4954264/7016067/818a8f18-dd10-11e4-86ea-4400cdb059eb.png)

**Comment by 2betop** [comment]
哦，我再看看

**Comment by 2betop** [comment]
不好意思，是我 demo 有问题， depsCombine 不会合并 异步依赖。而 index.html 只写了异步require。

来 `git pull` 一下，我改成以下写法了。

![image](https://cloud.githubusercontent.com/assets/2698393/7016203/3edbeba6-dd12-11e4-8778-e42a5b3bfe3f.png)

**Comment by BelinChung** [comment]
OK 了，我的项目也能正常产出 index.js 了
还有个问题是，怎么样能在 release 之后，去除掉标记依赖的注释？

**Comment by 2betop** [comment]
你说的是这类吧 `/*@require "jquery-ui/themes/base/core.css"**/`

**Comment by BelinChung** [comment]
@2betop 是的，我通过 fis-optimizer-html-minifier 移除注释的话，连 PLACEHOLDER 标记也干掉了，这样就出错了，所以问问有没有其他方法去移除它

**Comment by 2betop** [comment]
额，目前没好办法！

**Comment by oxUnd** [comment]
@BelinChung  PLACEHOLDER 换成一个不会被压缩干掉的标签？

**Comment by BelinChung** [comment]
@xiangshouding 这样也可以呀，但是自定义的 PLACEHOLDER FIS 能认吗？

**Comment by oxUnd** [comment]
@BelinChung 如果你用的是 Simple 的话，貌似有配置项吧？

**Comment by BelinChung** [comment]
搞定   ;)
Thanks
